# Generated by Django 2.2 on 2020-05-23 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(blank=True, max_length=140)),
                ('carModelType', models.CharField(blank=True, max_length=140)),
                ('purchaseDate', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasedCar', to='clients.Client')),
                ('soldBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
